//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aqwas.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feed()
        {
            this.UserFeeds = new HashSet<UserFeed>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> FeedDate { get; set; }
        public Nullable<bool> IsSubscribed { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFeed> UserFeeds { get; set; }
    }
}
